This technote has been migrated to the new format.
lsst-sitcom/sitcomtn-071 pull request #1
Opened 2024-07-02 13:21 UTC by craiglagegit

I migrated it by following the procedures at https://documenteer.lsst.io/technotes/migrate.html.  Everything seems OK.  I also put the analysis notebook in the notebooks directory of the technote.

2024-07-06 00:35 UTC, Kelks19 requested changes
It looks ok except for a few formatting corrections!

2024-07-06 00:35 UTC, Kelks19 commented on index.rst
> +.. abstract::
Remove this Abstract - The technote shows repeated Abstract subsections

2024-07-06 00:35 UTC, Kelks19 commented on index.rst
> -.. sectnum::
remove the `.. note::` as this is the final anlaysis

2024-07-06 00:35 UTC, Kelks19 commented on index.rst
> -.. sectnum::
Line 27 : Shouldn't it be 'Hertz'? I still keep getting confused .....

2024-07-06 00:35 UTC, Kelks19 commented on index.rst
> +The analysis and plots shown here were done using the notebook "StarTracker_Fast_Offsets_05Apr23.ipynb", which is in the notebooks directory of this technote.
Since it is the filename you can use ` :file:`pathname` `. This is the formatting we use for our documentation. It will be good to have uniformity across the technotes as well.

2024-07-06 00:35 UTC, Kelks19 commented on index.rst
>  The first step is to determine the offsets using the astrometry solutions as determined by RubinTV. FInding an astrometry solution for the fast camera images is difficult because the field of view is
"figure 1"--> "Figure 1"

2024-07-06 00:35 UTC, Kelks19 commented on index.rst
>  The first step is to determine the offsets using the astrometry solutions as determined by RubinTV. FInding an astrometry solution for the fast camera images is difficult because the field of view is
The following two Github links get displayed incorrectly on the html -- they are too long. You could re-format them to spread over 3 lines within the main text body width.

2024-07-08 13:11 UTC, craiglagegit commented on index.rst
> +.. abstract::
I did this.

2024-07-08 13:11 UTC, craiglagegit commented on index.rst
> -.. sectnum::
I fixed both of these.

2024-07-08 13:12 UTC, craiglagegit commented on index.rst
> +The analysis and plots shown here were done using the notebook "StarTracker_Fast_Offsets_05Apr23.ipynb", which is in the notebooks directory of this technote.
I did this.  Please check and see if this is what you want.

2024-07-08 13:13 UTC, craiglagegit commented on index.rst
>  The first step is to determine the offsets using the astrometry solutions as determined by RubinTV. FInding an astrometry solution for the fast camera images is difficult because the field of view is
I fixed the "figure 1".  On the links, I broke them into mulyiple lines, but this causes them to lose the link formatting.  I don't know any way to fix this.

2024-07-09 17:11 UTC, Kelks19 approved these changes
Only minor formatting corrections required! I have approved it-- once you are done  you are free to merge the PR

2024-07-09 17:11 UTC, Kelks19 commented on index.rst
> +:file: notebooks/StarTracker_Fast_Offsets_05Apr23.ipynb
This formatting is not working. Maybe the documenteer config for technotes is not picked up from  our official documentation. 

I suggest to keep it emphasized.

2024-07-09 17:11 UTC, Kelks19 commented on index.rst
> +https://github.com/lsst-ts/ts_observatory_control/blob/
Only half of the path is hyper-linked. You could just hyper-link the word "code" and include the path there.

2024-07-09 17:11 UTC, Kelks19 commented on index.rst
> + 65e62109e88185f16e08e24683914e08bf5c3119/python
Same as above - Only half of the path is hyper-linked. You could just hyper-link the word "code" and include the path there.

2024-07-09 17:13 UTC, Kelks19 commented on index.rst
> +The analysis and plots shown here were done using the notebook "StarTracker_Fast_Offsets_05Apr23.ipynb", which is in the notebooks directory of this technote.
It should have been emphasized. Can you please just revert it and leave it emphasized ?

2024-07-09 17:18 UTC, Kelks19 commented on index.rst
>  The first step is to determine the offsets using the astrometry solutions as determined by RubinTV. FInding an astrometry solution for the fast camera images is difficult because the field of view is
At this point in the `code`_ 

.. _code: https://github.com/lsst-ts/ts_observatory_control/blob/ 65e62109e88185f16e08e24683914e08bf5c3119/python /lsst/ts/observatory/control/base_tcs.py#L116

2024-07-16 18:54 UTC, merged